# See the languages documentation: https://docs.helix-editor.com/master/languages.html

[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
auto-format = true
formatter = {command = 'black', args = ["--quiet", "-"]}
config = ""
# Astro
[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
# roots = []
roots = ["package.json", "tsconfig.json", "jsconfig.json", ".git"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "astro-ls", args = ["--stdio"] }
# formatter = { command = "PRETTIERD_DEFAULT_CONFIG='/home/samus/.config/.prettierrc' prettierd", args = ["{0}"] }
formatter = { command = "prettierd", args = ["*.astro"] }
auto-format = true

[[grammar]]
name = "astro"
source = { git = "https://github.com/virchau13/tree-sitter-astro", rev = "5f5c3e73c45967df9aa42f861fad2d77cd4e0900" }

# React Javascript
[[language]]
name = "jsx"
auto-format = true
[[language]]
name = "html"
auto-format = false

# Rust
[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
shebangs = ["run-cargo-script"]
language-server = { command = "rust-analyzer" }
formatter = { command = "rustfmt" }
indent = { tab-width = 2, unit = "  " }

[language.config]
checkOnSave = { command = "clippy" }

[language.debugger]
name = "lldb-vscode"
transport = "stdio"
command = "lldb-vscode"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}" }

[[language.debugger.templates]]
name = "binary (terminal)"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", runInTerminal = true }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [ "pid" ]
args = { pid = "{0}" }

[[language.debugger.templates]]
name = "gdbserver attach"
request = "attach"
completion = [ { name = "lldb connect url", default = "connect://localhost:3333" }, { name = "file", completion = "filename" }, "pid" ]
args = { attachCommands = [ "platform select remote-gdb-server", "platform connect {0}", "file {1}", "attach {2}" ] }

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "a360da0a29a19c281d08295a35ecd0544d2da211" }

# Toml
[[language]]
name = "toml"
scope = "source.toml"
roots = ["*.toml"]
auto-format = true
injection-regex = "toml"
file-types = ["toml"]
comment-token = "#"
language-server = { command = "taplo", args = ["lsp", "stdio"] }
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "toml"
source = { git = "https://github.com/ikatyang/tree-sitter-toml", rev = "7cff70bbcbbc62001b465603ca1ea88edd668704" }

# Yaml
[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yml", "yaml"]
roots = []
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "yaml-language-server", args = ["--stdio"] }
injection-regex = "yml|yaml"

# Lua
[[language]]
name = "lua"
roots = [".luarc.json", ".luacheckrc", ".stylua.toml", "selene.toml",".git"]
#language-server = { command = "luahelper-lsp", args = ["-mode", "1", "-logflag", "1"] }
language-server = { command = "lua-language-server"}
# ref https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/sumneko_lua.lua
# https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#sumneko_lua
# https://learnxinyminutes.com/docs/toml/
config = {"telemetry" = { "enable" = false }}

# Zig
[[language]]
name = "zig"
auto-format = true
language-server = { command = "zls"}
indent = {tab-width=2,unit="  "}

# Haskell
[[language]]
name = "haskell"
auto-format = true
indent = {tab-width=2,unit="  "}

# C++
[[language]]
name = "cpp"
auto-format = true
indent = {tab-width = 2, unit = "  "}

# C
[[language]]
name = "c"
auto-format = true
indent = {tab-width = 2, unit = "  "}
